sctplab/usrsctp

- programs/ekr_client.c
- programs/ekr_loop.c
- programs/ekr_peer.c
- programs/ekr_server.c
- programs/rtcweb.c
- programs/tsctp.c
- usrsctplib/user_malloc.h
- usrsctplib/user_mbuf.c
- usrsctplib/user_recv_thread.c
- usrsctplib/user_socket.c
Let ekr_loop exit on errors and stop the ekr_* execution if not enough arguments have been supplied.
> Programs improvements

- usrsctplib/netinet/sctputil.c
Thanks to Eugen-Andrei Gavriloaie for reporting the issue and proving detailed
information to find the root of the problem.
> Fix issue #86

- usrsctplib/netinet/sctp_callout.c
- usrsctplib/netinet/sctp_pcb.h
- usrsctplib/netinet/sctp_usrreq.c
> Fix data race around timer_thread_should_exit.

- usrsctplib/netinet/sctp_output.c
- usrsctplib/user_socket.c
Tested on FreeBSD, Linux, Windows7 and MacOsX
> Set DF Flag correctly

- usrsctplib/netinet/sctp_bsd_addr.c
- usrsctplib/user_mbuf.c
- usrsctplib/user_mbuf.h
Refactoring of sctp_get_mbuf_for_msg in userland.
Possibility to build mbuf chains
> Mbuf chains

- CMakeLists.txt
- programs/CMakeLists.txt
- programs/rtcweb.c
- usrsctplib/CMakeLists.txt
- usrsctplib/netinet/sctp_output.c
This PR extends PR #249
- more strict compiler warning level (W3 -> W4)
- fixed compiler warnings for WIN64 build
> Windows improvements

- usrsctplib/user_recv_thread.c
Continue normal execution when recvmsg is interrupted by delivery of a signal
> Handle EINTR error in the receive functions

- programs/CMakeLists.txt
- programs/chargen_server_upcall.c
- programs/http_client_upcall.c
- programs/tsctp.c
- programs/tsctp_upcall.c
* http_client_upcall : check return value 
* chargen_server_upcall : clarified variable declaration
* tsctp_upcall : tsctp using upcall API
* tsctp: refactoring and a bugfix
> tsctp_upcall and some fixes

- programs/tsctp_upcall.c
- usrsctplib/usrsctp.h
> Windows ssize_t fix

- programs/Makefile.am
Three example programs were missing in Makefile.am
> Makefile.am - include all example programs

- usrsctplib/netinet/sctp_cc_functions.c
Fixes https://github.com/sctplab/usrsctp/issues/395
> Fix crash with HTCP

- meson.build
- usrsctplib/meson.build
> Fix incorrect source include of ifaddrs.c and stylistic changes

- usrsctplib/user_socket.c
> fix truncated writing warning

- meson.build
Fixes #493 
I guess it makes sense to add a GitHub action for Meson, too, so this doesn't happen. Should I write that?
> Clean Meson build file

- programs/programs_helper.c
Call fflush() in debug log function.
> fflush() in debug log

- meson.build
> Fix oversight: Don't undefine platform specific defines

- usrsctplib/CMakeLists.txt
> Fix #545 - remove .lib extension

- usrsctplib/user_environment.c
@mohatry, @saurik, this should address your concerns. Tested on Ubuntu 14.04 (kernel 3.13), with both the "__NR_getrandom not defined" and "__NR_getrandom defined but fails at runtime" code paths.
> Fall back to using urandom on Linux if getrandom isn't available.

- programs/client_upcall.c
Strlen will just look for a null character for its calculations. so this code doesn't make sense.
but it is dangerous because if the code is changed as a result of the development of the project, then the function may go beyond the allocated memory.
I suggest deleting this call.
> removal of meaningless but dangerous code

- CMakeLists.txt
- cmake/FindMbedTLS.cmake
- usrsctplib/CMakeLists.txt
- usrsctplib/netinet/sctp_sha1.c
- usrsctplib/netinet/sctp_sha1.h
Hi, 
I added the mbedtls sha1 support. Hope this can help others use this lib with mbedtls.
thanks.
> Add mbedtls sha1 support

- usrsctplib/netinet/sctputil.c
Before this change, sac_error would always be set to 0 in case of errors such as protocol violations.
When we receive an ABORT, the error code is propagated just fine to the notifications, but  when the local client is emitting an ABORT, it would always be 0.
> Propagate error cause code to notifications

- usrsctplib/netinet/sctp_cc_functions.c
- usrsctplib/netinet/sctp_output.c
> Fix some instances of -Wunusued-but-set-variable.

- usrsctplib/netinet/sctp_input.c
This should fix https://github.com/sctplab/usrsctp/issues/697.
> Lock ACCEPT_LOCK before checking socket->so_head.
