sctplab/usrsctp

.gitignore
programs/ekr_client.c
programs/ekr_peer.c
programs/ekr_server.c
programs/rtcweb.c
programs/tsctp.c

Removed deprecated functions like inet_addr() to get rid of compiler warnings.

Fix compile warnings for deprecated functions

---

Manual.md

for easier access directly on Github. might be nice to link to this from the ReadMe.
supersedes #5.
again, happy to edit further if needed.

Manual.md: convert Manual.tex to markdown

---

usrsctplib/netinet/sctp_auth.c
usrsctplib/netinet/sctp_input.c
usrsctplib/netinet/sctp_os_userspace.h
usrsctplib/netinet/sctp_output.c
usrsctplib/netinet/sctp_pcb.c
usrsctplib/netinet/sctp_usrreq.c
usrsctplib/netinet/sctputil.c

GCC 5 only allows the use of `__FUNCTION__` as an extension. so
it must be prefixed by `__extension__`, though the standard (since C99)
`__func__` is preferred. So use the latter since -std=c99 is required anyway.
Fixes the following errors:
~~~~
In file included from ./netinet/sctp_os.h:72:0,
from netinet/sctp_auth.c:38:
netinet/sctp_auth.c: In function 'sctp_auth_key_acquire':
netinet/sctp_auth.c:563:4: error: ISO C does not support '__FUNCTION__' predefined identifier [-Werror=pedantic]
__FUNCTION__, (void *)stcb, key_id, skey->refcount);
^
./netinet/sctp_os_userspace.h:560:31: note: in definition of macro 'SCTP_PRINTF'
SCTP_BASE_VAR(debug_printf)(__VA_ARGS__); \
^
netinet/sctp_auth.c:561:3: note: in expansion of macro 'SCTPDBG'
SCTPDBG(SCTP_DEBUG_AUTH2,
^
netinet/sctp_auth.c: In …

Fix compilation with GCC 5

---

usrsctplib/netinet/sctp_callout.c
usrsctplib/netinet/sctp_callout.h
usrsctplib/netinet/sctp_os_userspace.h

Caught by a data race detector.

Data racing fix on reading ticks in sctp_callout.

---

usrsctplib/netinet/sctp_bsd_addr.c
usrsctplib/netinet/sctp_callout.c
usrsctplib/netinet/sctp_os_userspace.h
usrsctplib/netinet/sctp_userspace.c
usrsctplib/user_recv_thread.c

The Windows CreateThread API expects a function that is __stdcall.
Passing it a normal function pointer that is __cdecl causes crashes in
some situations.
There are more instances of this bug in programs/, but they pass
arguments and so they are not easy to adapt through sctp_thread_create.
More context: http://crbug.com/562308

Fix calling convention mismatch for thread creation argument

---

programs/tsctp.c

Only checking for !done could cause a close before sending EOF.
https://github.com/sctplab/usrsctp/blob/master/programs/tsctp.c#L275
tsctp should wait until the last message has been sent.

Fix tsctp sender when using callbacks

---

usrsctplib/netinet/sctp_userspace.c

With this small change, this code should build with other libc's on linux (eg uClibc).

use prctl instead of (glibc-specific) pthread_setname_np on Linux

---

usrsctplib/netinet/sctp_bsd_addr.c

Until da6f8ba, sctp_init_ifns_for_vrf() was using the MALLOC and FREE
macros, using respectively HeapAlloc and HeapFree. da6f8ba changed the
allocations to use GlobalAlloc, but didn't change the deallocations to
use the symmetric GlobalFree.
This doesn't seem to cause direct problems, but when wrapping one family
of allocation functions, the dissymmetry causes allocator mismatch
problems.
Moreover, the MALLOC macro being unused, it might as well be removed,
along the FREE macro, so that both allocations and deallocations use one
API explicitly.
It should be noted, for a precedent, that sctp_userspace.c uses
GlobalAlloc/GlobalFree too, with no wrapping with macros.

Free pAdapterAddrs with GlobalFree in sctp_init_ifns_for_vrf()

---

usrsctplib/netinet/sctp_output.c

sctp_add_stream_reset_result was being called before chunk_length
was set, causing the result to be written to an undefined location
in memory.

Fixing heap overflow in sctp_send_deferred_reset_response.

---

usrsctplib/usrsctp.h

74d255f made the list of platforms with *_len as first member explicit. One has to adjust it every time a new BSD descendant is supported like in 2a986e7. DragonFly for some reason was missed.

Add more systems for BSD-style struct sockaddr_conn

---

programs/rtcweb.c
usrsctplib/netinet/sctp.h
usrsctplib/user_ip_icmp.h
usrsctplib/usrsctp.h

The code is setting the packing alignment with
`  #pragma pack (push, 1)`
and would then reset it with
`  #pragma pack ()`
The latter directive resets the packing alignment to the default value,
which means if some other packing alignment was in effect before the
'push', that is now lost.
This patch resets the packing alignment with
`  #pragma pack (pop)`
instead, to patch the 'push' operation.
(This problem was found in a Chromium build by a new Clang warning,
-Wpragma-pack.)

Use '#pragma pack (pop)' instead of '#pragma pack ()'

---

usrsctplib/netinet/sctp_header.h

Somehow I missed this in my previous patch.

Fix one remaining #pragma pack()

---

programs/daytime_server.c
programs/discard_server.c
programs/echo_server.c
programs/ekr_server.c

Replaced some magic numbers (e.g. port, sleeptime) with preprocessor directives (macros).
(This may be helpful for users who still do not know the usual service-ports.)

Replaced some magic numbers with preprocessor directives

---

usrsctplib/netinet/sctp_os_userspace.h

Fuchsia is a new operating system (https://fuchsia.googlesource.com/)
that supports pthreads for threading. CMake has support for Fuchsia:
https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/Platform/Fuchsia.cmake
so this wires up the #define.

Add pthread.h include for os_Fuchsia

---

Manual.md
Manual.tex

This adds discussion of the parameter `ulp_info` and updates some
function and callback signatures.
Fixes issue #198.

manual: Improve docs for usrsctp_socket.

---

CMakeLists.txt
usrsctplib/user_atomic.h
usrsctplib/user_socket.c

This PR adds "-Wstrict-prototypes" check if supported and fixes related warnings.
See #207

Add compiler check "-Wstrict-prototypes" and fix warnings

---

usrsctplib/netinet/sctp_pcb.c

In AF_CONN case cast to sockaddr_conn instead of sockaddr_in6

Fix cast in sctp_findassociation_ep_addr

---

usrsctplib/netinet/sctputil.c

Increment should use sizeof(struct sockaddr_conn) instead of
sizeof(struct sockaddr_in6).

Fix increment in sctp_connectx_helper_add

---

usrsctplib/user_socket.c

localtime isn't thread-safe, since it returns a pointer to a
statically-allocated struct, whereas localtime_r takes the address of a
user-allocated struct.
This is only used in usrsctp_dumppacket.

Switching from localtime to localtime_r on non-Windows platforms.

---

usrsctplib/user_socket.c

`#pragma GCC diagnostic push` and `#pragma GCC diagnostic pop` were added in [gcc 4.6](https://gcc.gnu.org/gcc-4.6/changes.html). 
see also:
https://stackoverflow.com/questions/16555585/why-pragma-gcc-diagnostic-push-pop-warning-in-gcc-c
https://stackoverflow.com/questions/28681305/pragma-ignored-in-g-and-clang

Fix a build fails with gcc 4.5

---

Makefile.am
configure.ac

Hi,
These are some minor changes to the build system so that:
- Building the example programs can be disabled
- autoreconf can be used to initialise the build system instead of using the ./bootstrap script as autoreconf correctly uses the environment supplied by Yocto (and boostrap.sh does not)

Minor build system fixes

---

usrsctplib/user_malloc.h

Fixes the following error when building with GCC and using MinGW's ucrtbase:
```
/home/andoni/mingw/linux/multilib/x86_64-w64-mingw32/sysroot/mingw/include/minwindef.h:173: note: this is the location of the previous definition
#define max(a, b) (((a) > (b)) ? (a) : (b))
In file included from user_mbuf.h:40,
from user_mbuf.c:44:
user_malloc.h:49:18: error: duplicate 'unsigned'
#define uint32_t unsigned __int32
^~~~~~~~
user_malloc.h:50:18: error: duplicate 'unsigned'
#define uint64_t unsigned __int64
^~~~~~~~
In file included from /home/andoni/mingw/linux/multilib/x86_64-w64-mingw32/sysroot/mingw/include/crtdefs.h:10,
from /home/andoni/mingw/linux/multilib/x86_64-w64-mingw32/sysroot/mingw/include/stdio.h:9,
from user_mbuf.c:38:
user_malloc.h:50:27: error: 'long long long' is too long for …
```

Fix build with MinGW and the ucrtbase CRT

---

programs/http_client.c
programs/http_client_upcall.c
usrsctplib/user_socket.c

Improved error handling for the http_client and http_client_upcall examples.
The return codes distinguish between refused connections, timed out connections and other errors.
Also fixes a compiler warning:
```
In file included from /home/buildbot/bs-sctplab/netbsd/build/usrsctplib/netinet/sctp_os_userspace.h:448:0,
from /home/buildbot/bs-sctplab/netbsd/build/usrsctplib/netinet/sctp_os.h:74,
from /home/buildbot/bs-sctplab/netbsd/build/usrsctplib/user_socket.c:35:
/home/buildbot/bs-sctplab/netbsd/build/usrsctplib/user_socket.c: In function 'usrsctp_connect':
/home/buildbot/bs-sctplab/netbsd/build/usrsctplib/user_malloc.h:191:26: error: 'sa' may be used uninitialized in this function [-Werror=maybe-uninitialized]
#define FREE(addr, type) free((addr))
^ …
```

Improved error handling for examples and fixed a compiler warning

---

Manual.md

Two Links missed leading `http(s)://` and were broken.
All links to `tools.ietf.org` now consistently use https.

Fix broken links, Make URLs' protocols consistent

---

usrsctplib/netinet/sctp_output.c

Fixes an issue introduced in f4166b347188af0de05fa70456042ef8a792cdd7,
the scope must be closed outside of the FreeBSD clause, as it is opened
outside of it.

sctp_output: fix non-FreeBSD compilation

---

gen-def.py
meson.build

From the output of "dumpbin /linkermember" run on the static version of usrsctp generate .def file with function names to export from the DLL.

Fix MSVC Meson build

---

programs/ekr_loop_offload.c
programs/ekr_loop_upcall.c
programs/rtcweb.c
usrsctplib/netinet/sctp_asconf.c

Some fixes of minor spelling issues reported by Lintian:
I: libusrsctp1: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libusrsctp.so.1.0.0 queing queueing
I: libusrsctp-examples: spelling-error-in-binary usr/bin/ekr_loop_offload Messsage Message
I: libusrsctp-examples: spelling-error-in-binary usr/bin/ekr_loop_upcall Messsage Message
I: libusrsctp-examples: spelling-error-in-binary usr/bin/rtcweb unkown unknown

Fixed spelling issues reported by Lintian

---

usrsctplib/usrsctp.h

Added missing SCTP_DATA_{LAST_FRAG,NOT_FRAG} flags

---

usrsctplib/netinet/sctp_callout.c
usrsctplib/netinet/sctp_callout.h

I've started investigation of possible fix to #131 myself. 
To understand how to fix an issue I've started to familiarize myself with timer implementation from  [`sctp_callout.c`](https://github.com/sctplab/usrsctp/blob/256ce79d3122ce92d73edb2d46f8eb6da664aa69/usrsctplib/netinet/sctp_callout.c), where changes suspected to introduce bug #131. During learning I've noticed some enhancements (in my opinion) can be done to the timer implementation. So this PR is very tiny and my first PR to this repository with small enhancement to a source code for better readability, just to get acquainted with contribution process to this repo.

Rename delta to elapsed_ticks.

---

usrsctplib/netinet/sctp_callout.c
usrsctplib/netinet/sctp_callout.h

Type of `to_ticks` of function `sctp_os_timer_start` has changed to `uint32_t`. It was supposed to be done as part of #393, but accidentally forgotten.

Change type of to_ticks in sctp_os_timer_start to uint32_t.

---

CMakeLists.txt

`Visual Studio` has support of `CMake` projects with clang toolchain on `Windows`, but currently `usrsctp` cmake file passes clang-specific switches to `clang-cl.exe`, which expect the same switches format as `cl.exe`.
With proposed changes `clang-cl.exe` will be treated as `cl.exe` with small exception to extra warnings provided by clang.

Added initial support of compilation by clang-cl.exe on Windows.

---

meson.build
usrsctplib/meson.build

commit 48fee387dd98748bd3b4ed4e1dd80b016a228b17:
```
meson: add support for android/ios host_system
```
commit 5f1a0f75b3406688d8ad95cf616e43244a9c820e:
```
build: include ifaddrs.c definition for android
```
With these changes libusrsctp builds correctly on Android with Meson.
CC: @ystreet

meson: Fixes needed to build on Android

---

meson.build

Otherwise we get linker errors for ws2_32, etc.

meson: Need dependencies while linking shared library too

---

meson.build

have_sconn_len was always false because compiler.has_member generates a C file
which does not build because the compiler can't include "usrsctp.h". Fixed by
specifying the include path.

meson: Fix sconn_len detection (#411)

---

CMakeLists.txt
usrsctplib/CMakeLists.txt

This PR suggests two small changes to `CMakeLists` to allow importing usrsctp as submodule with `add_subdirectory`:
- Replace `CMAKE_SOURCE_DIR` with `CMAKE_CURRENT_SOURCE_DIR`
- Export `usrsctplib` as include directory
These changes currently make for a cleaner import of usrsctp in my project [libdatachannel](https://github.com/paullouisageneau/libdatachannel) and should not introduce unwanted side effects.

CMake changes to import usrsctp as submodule

---

usrsctplib/netinet/sctp_callout.c
usrsctplib/netinet/sctp_callout.h
usrsctplib/netinet/sctp_os_userspace.h
usrsctplib/netinet/sctp_pcb.c
usrsctplib/netinet/sctp_userspace.c

These commits attempted to fix a crash caused by freeing a timer's memory while the timer's callout is currently executing (meaning `sctp_timer_stop` couldn't stop it).
The attempted solution was to wait for the callout's completion in `sctp_timer_stop`. However, in the very likely case that the callout is waiting to acquire locks that the thread calling `sctp_timer_stop` owns, this will result in a deadlock.
This has a chance to happen not only when timers are being freed, but *any* time `sctp_timer_stop` is called. Effectively trading a low risk of a crash for a high risk of a deadlock.
Reverting these commits will fix #414 and fix #325.
Note that this PR attempts to solve the original problem in a different way, using pre-existing reference counts: …

Revert series of callout guard commits

---

fuzzer/fuzzer_connect.c

The <sys/time.h> header is unused and is breaking the Windows build.

Get rid of unnecessary include in fuzzer.

---

usrsctplib/netinet/sctp_usrreq.c
usrsctplib/user_recv_thread.c

Fixes a busy loop of the usrsctp UDP recv thread attempting to shutdown
usrsctp with usrsctp_finish().
Usually, destroying the udp socket in recv_thread_destroy() would result
in the udp receive thread returning an error (-1) with errno set to
(-9) EDABF.  In other cases, sometimes recvmsg would return 0 without an
error being reported in errno.  My assumption here is that the fd number
would be reused for some other purpose.
Explicitly set the socket/fd variables to -1 before performing a
close()/closesocket() on them so that any future recv*() calls will
return with an error.

user_recv_thread: set fd to -1 before closing

---

usrsctplib/netinet/sctp_pcb.h
usrsctplib/netinet/sctp_usrreq.c
usrsctplib/user_socket.c
usrsctplib/usrsctp.h

Can be used to access `ulp_info` from within `send_cb`.
Fixes #465.

Add usrsctp_get_ulpinfo getter.

---

programs/st_client.c
usrsctplib/user_socket.c
usrsctplib/usrsctp.h

Currently `usrsctp_handle_timers` passes delta value came from user application as is into `sctp_handle_tick`.
This only work correctly when delta value is measured in ticks.
As long as there is no way (or I can't find one) to figure out how ticks translated to wall clock time there is no way to use of this method pass correct ticks value.
I believe it is correct to allow user to pass elapsed milliseconds, which is converted by library to internal notion of time - ticks.

Adjust `usrsctp_handle_timers` signature and implementation

---

usrsctplib/user_socket.c

Not sure how that happen, but in #470 I've used macro which no longer exists and it went unnoticed by me.
So, this PR is fixing the issue.

Fixed compilation due usage of non existing macro

---

.github/workflows/build-with-cmake.yml

This PR switches from "Unix Makefiles" to "Ninja" to when perform build.
Ninja has an advantage of automatic build parallelization, so builds done by `GitHub Actions` must be faster.

GitHub Actions: switch to Ninja from "Unix Makefiles"

---

.github/workflows/build-with-cmake.yml

I've observed problems with existing `GitHub Actions` configuration I've proposed.
1. Sometimes `CMake` installation failed with `API limit error`. It is occurred that `GitHub Actions` runners has pre-installed `CMake` which could be used.
2. Sometimes (in my fork) I've observed `Ninja` installation failure. As long as I've added ninja to get automatic parallelization I believe that can be traded off by using default generator with `CMake` switch `--parallel` with hard coded number of `CPU`s, which is `2` for `GH Actions` runners. 
These changes should improve stability of the build. An maybe duration of builds will be reduced, because now additional SW is installed on runners.

GitHub actions: CMake is preinstalled. CPU count is fixed.

---

programs/tsctp.c

Adds the parameter -d to be able to specify an update time x. If specified, the receiver prints every x seconds the throughput of the last x seconds.

tsctp: add parameter to get the current throughput periodically

---

.github/workflows/build-with-cmake.yml

This change will help understand why sometimes build is failed.

GitHub Actions: Make CMake builds more vebose

---

programs/chargen_server_upcall.c
programs/daytime_server.c
programs/daytime_server_upcall.c
programs/discard_server_upcall.c
programs/echo_server_upcall.c
programs/ekr_server.c

Many of the programs end in a "while (1) { sleep(1); }" or similar
loop, followed by code to close the socket that will never be executed.

Fix -Wunreachable-code in programs/

---

programs/client_upcall.c
programs/discard_server.c
programs/discard_server_upcall.c
programs/echo_server.c
programs/echo_server_upcall.c
programs/ekr_client.c
programs/ekr_peer.c
programs/ekr_server.c
programs/programs_helper.c
programs/rtcweb.c
programs/st_client.c
programs/tsctp.c

On Windows, `ntohl` returns an `unsigned long` instead of `uint32_t`, so it expects a "%lu" print format specifier instead of "%u". Fixed by casting to `uint32_t`.

Fix gcc/clang type mismatch warnings on Windows

---

usrsctplib/user_environment.c

Our build system already defines _CRT_RAND_S, so this was resulting in -Wbuiltin-macro-redefined.
If you prefer, I can define _CRT_RAND_S through the usrsctp build files; this was just a lot easier.

Avoid duplicate definition of _CRT_RAND_S.

---

usrsctplib/user_environment.c

Doing this because getrandom wasn't added to glibc until 2.25.

Call getrandom via syscall directly on Linux.

---

CMakeLists.txt
fuzzer/CMakeLists.txt
programs/CMakeLists.txt
programs/tsctp.c
usrsctplib/CMakeLists.txt

... and an linter fix for an uninitialized variable.
Fixes #542

Use CMAKE's BUILD_SHARED_LIBS flag to build shared library

---

usrsctplib/user_environment.c

MSan doesn't realize that the syscall initialized the output buffer, so
this is necessary to avoid MSan errors when generating random numbers on
Linux.

Call __msan_unpoison after syscall(__NR_getrandom, ...).

---

programs/tsctp.c
usrsctplib/user_socket.c

Fix compile problem with uninitilized variables when MinGW is used for the release build.

MinGW release build - initialize variables

---

usrsctplib/netinet/sctp_userspace.c

We have an LLVM-based Windows toolchain that doesn't like uppercase library names.

Lowercase reference to iphlpapi.lib

---

usrsctplib/user_environment.c

openssl's random number generation code is more robust, and in the case
of building with chromium, is able to bypass sandbox restrictions that
prevent opening /dev/urandom.

Add optional SCTP_USE_OPENSSL_RAND define to use openssl's RNG.

---

usrsctplib/CMakeLists.txt

Fixed installation on other than Ubuntu GNU/Linux distributions.
Fedora and other GNU/Linux distributions use different $libdir prefixes. Now it can be installed on any GNU/Linux distributions.

Fixed installation on other than Ubuntu GNU/Linux distributions

---

usrsctplib/user_environment.h

Informs the compiler that the function never returns, which fixes a -Wsometimes-uninitialized warning.

Add __declspec(noreturn) to terminate_non_graceful() on Windows

---

configure.ac
meson.build
usrsctplib/CMakeLists.txt
usrsctplib/Makefile.am

Unified version and soversion between all supported build systems.
Closes #564. Closes #561.

Unified version and soversion between all supported build systems

---

Manual.md

It seems to me that the type for SCTP_REMOTE_UDP_ENCAPS_PORT is checked as the struct, `sctp_udpencaps`, and not an `int` as described in the documentation.
https://github.com/sctplab/usrsctp/blob/279a68fd6f5b8b913bd19ca99342f5f3e285a6fe/usrsctplib/netinet/sctp_usrreq.c#L7346

Correct option type for UDP encapsulation port

---

usrsctplib/netinet/sctp_input.c

Unless returning after `sctp_abort_an_association`.

Unlock TCB whenever returning early from sctp_process_cookie_existing.

---

CMakeLists.txt
configure.ac
meson.build
usrsctplib/user_recv_thread.c

To support cross-compiling for e.g. iOS using Apple's SDKs.

Add support for Apple SDKs missing net/route.h

---

meson.build

This is the canonical way of doing it, `-Wall` is added with `warning_level=1`, `-Wextra` with `warning_level=2`.
Without this change recent version of Meson produces warnings:
```
usrsctp| ../subprojects/usrsctp-59bd3c2fc5a43ac60cd7817aa1ad68c9d95cf376/meson.build:42: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
usrsctp| ../subprojects/usrsctp-59bd3c2fc5a43ac60cd7817aa1ad68c9d95cf376/meson.build:42: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
```

Replace warning flags in Meson with `warning_level`

---

usrsctplib/usrsctp.h

I do not necessarily know what I'm doing, but I think this fixes #600 and stops colliding with `std::*_t` in C++ projects.

Change defines to type aliases for better compatibility

---

Manual.md
README.md

`usrsctp` 0.9.5.0 has been tested/used successfully on
OpenBSD/amd64 7.0 -CURRENT as of today in conjunction with
the official Telegram Desktop client.

Mention OpenBSD support

---

usrsctplib/CMakeLists.txt

The usrsctp library uses threads, but building it with cmake does not
link against the system's thread library.
Use cmake's "Threads" package as usual to deal with all supported
platforms.
(autoconf's configure.ac correctly adds `-pthread` to CFLAGS.)
This is needed because programs which do not use threads themselves but
link against usrsctplib will otherwise fail to link since `pthread_*`
symbols used in libusrsctp.so are not resolved.
programs/CMakeFiles.txt avoids this problem by unconditionally using the
"Threads" package for every program including those that do not use
threads themselves.

cmake: usrsctplib: link against threads library

---

usrsctp.pc.in

Follow 40e35a7 "cmake: usrsctplib: link against threads library (#644)";
this is not in "Libs:" since programs do not need to link against
pthreads themselves.
See https://people.freedesktop.org/~dbn/pkg-config-guide.html

usrsctp.pc: register pthread

---

.github/workflows/cifuzz.yml

Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which usrsctp already runs.

GitHub Actions: Add CIFuzz integrations

---

usrsctplib/user_environment.c

As it has both device entries and they provide the same functionality.
(I totally missed this when skimming the [documentation](http://www.qnx.com/developers/docs/7.0.0/index.html#com.qnx.doc.neutrino.utilities/topic/r/random.html), and it wasn't until today that I happened to notice the other device entry.)

Simplify init_random() to remove QNX special-case

---

usrsctplib/netinet/sctp_asconf.c

The param type looks wrong for aa_del, correcting the param type used for delete to SCTP_DEL_IP_ADDRESS.

bugfix: nat-state-update for ipv4

---

usrsctplib/user_socket.c

The declarations for `usrsctp_sysctl_set_sctp_ootb_with_zero_cksum()` and `usrsctp_sysctl_get_sctp_ootb_with_zero_cksum()` exist, but their definitions were missing, causing an error.

Add definition for sctp_ootb_with_zero_cksum

---

usrsctplib/netinet/sctp_output.c

The `use_zero_crc` flag is already considered for AF_INET address family. This commit ensures that when transmitting using sockets created with the AF_CONN address family, crc32c calculation is skipped based on this flag.

Extend use_zero_crc check to AF_CONN sockets

---

configure.ac

This makes -g -O2 the default build mode.

Separate --enable-debug from --enable-opt in configure.

---

usrsctplib/netinet/sctputil.c

This makes the information for timer execution match that for timer scheduling.

Enhance timer execution debug log.

---

usrsctplib/netinet/sctp_os_userspace.h

Looks like `WORDS_BIGENDIAN` may not be defined, and the fallback is to little-endian. We know for sure that Darwin is BE on powerpc, always.

sctp_os_userspace.h: ensure WORDS_BIGENDIAN is defined on powerpc darwin
